name: Build and push Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

env:
  IMAGE: ghcr.io/${{ github.repository }}/klage-redis
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd build
          docker build --tag ${IMAGE}:${{ github.sha }} --tag ${IMAGE}:latest .
          docker login ghcr.io -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE} --all-tags


